### ISSUE TITLE
Incorrect @swc/jest description 

### ISSUE THREAD

**Issue by pcjmfranken** [swc-project/website#134]
From https://github.com/swc-project/website/blob/35da4af2ff98326e2e8d9b894d23c51603e7aeaf/pages/docs/usage/jest.md?plain=1#L3:
> To make your Jest tests run faster, you can swap out the default JavaScript-based runner (`ts-jest`) for a [drop-in Rust replacement](https://github.com/swc-project/jest) using SWC.

<br/>

The "default" Jest runner for TypeScript is actually[^1] Babel with `@babel/preset-typescript`.

Neither `@swc/jest` nor the Babel TypeScript setup support type-checking, whilst `ts-jest` does.

This makes `@swc/jest` a drop-in replacement for the actual default runner, but not for the one that is mentioned :)

[^1]: https://jestjs.io/docs/getting-started#using-typescript

**Comment by leerob** [comment]
Fixed here - thank you!

https://github.com/swc-project/website/pull/139
