### ISSUE TITLE
Website is not Mobile responsive 

### ISSUE THREAD

**Issue by kumard3** [swc-project/website#168]
<img width="1440" alt="Screenshot 2022-05-26 at 12 32 38 AM" src="https://user-images.githubusercontent.com/62591080/170349905-b0571f21-2adb-487c-b15b-afd92291ce06.png">
The Website is Not Responsive on the mobile screens.
I wanted to contribute to this section .

**Comment by kdy1** [comment]
Oh, I see.
It would be really nice if you contribute 😄

**Comment by kumard3** [comment]
> Oh, I see. It would be really nice if you contribute 😄

hey man, I found the error, so it is happening because of the version of Nextra. so can i upgrade the version of Nextra ?

**Comment by kdy1** [comment]
Yeah of course
