### ISSUE TITLE
Migrate website from Docusaurus Verion 1 to version 2

### ISSUE THREAD

**Issue by anshulrgoyal** [swc-project/website#17]
# Description
New version has better looks and feel and comes with support for MDX and other plugins.

**Comment by kdy1** [comment]
I tried it but it seems like to be in very early stage.
I will do this is future

**Comment by anshulrgoyal** [comment]
I work on docusaurus I will migrate this website as a test for our migration tool :)

**Comment by anshulrgoyal** [comment]
If u are interested I can make a PR :)

**Comment by kdy1** [comment]
Of course I'm interested. Thanks a lot!

**Comment by mfeckie** [comment]
@kdy1  I think that #27 closes this issue?

**Comment by kdy1** [comment]
@mfeckie You are right, thanks!
