### ISSUE TITLE
How Do I Migrate from Babel to swc??

### ISSUE THREAD

**Issue by fujiyamaorange** [swc-project/website#205]
@kdy1 
Hello!
Recently I tried to use swc instead of babel and I found [this page](https://swc.rs/docs/migrating-from-babel).
However I can't migrate from babel becase I could not find any npm packages which takes the place of `babel-preset-env`.
How do I migrate from babel to swc??

**Comment by kdy1** [comment]
https://swc.rs/docs/configuration/compilation#env

**Comment by fujiyamaorange** [comment]
Thank you kdy1!!
