### ISSUE TITLE
Playground not rendering

### ISSUE THREAD

**Issue by tonywu6** [swc-project/website#272]
Looks like the playground at https://swc.rs/playground isn't rendering correctly. https://play.swc.rs/ seems fine

<img width="1496" alt="Screenshot 2024-10-29 at 7 41 02 PM" src="https://github.com/user-attachments/assets/17fc6520-ccb8-49b3-8a4b-c85332af7a1d">

**Comment by tonywu6** [comment]
@kdy1 sorry for ping but I think this could be fixed by just renaming `apps/website/pages/playground/index.md` to `apps/website/pages/playground/index.mdx`

**Comment by kdy1** [comment]
@tonywu6 Thanks!
