### ISSUE TITLE
How often plugins site is updated? 

### ISSUE THREAD

**Issue by timofei-iatsenko** [swc-project/website#273]
It seems that the plugins site is not updated for a quite a long time. The latest available version of `next` is 15.0.0-rc.0 and it seems compatibility ranges of swc_core itself is also outdated. 

Am I missing something?

**Comment by kdy1** [comment]
It's not outdated. See https://github.com/swc-project/crawl-core-version

**Comment by kdy1** [comment]
Actually, the DB model for range is misdesigned, I guess. The range file itself is up-to-date, but it does not have upper bound. https://github.com/swc-project/website/blob/443a4bf7f641e1ebfa3e377c3626dee8fe3beb60/apps/plugins/data/ranges.json

**Comment by timofei-iatsenko** [comment]
It seems compatibility ranges also incorrect, because there were a breaking changes between `0.98.0` and `0.106.3` 

The Next 15 doesn't work with a plugin built with `0.101.4` but works with a `0.106.3`

**Comment by kdy1** [comment]
I 

- updated range data
- removed wrong range (`0.98.0 ~ *`)
- ran auto-update


but I found that `swc_core` detection is wrong

**Comment by timofei-iatsenko** [comment]
Thanks, it seems the new range is appeared on the site. One more thing I wanted to mention, that from the user's perspective there might be difficulties to find a proper version of a runtime.  

As far as I understand, `next@15.0.0-rc.0` is the last version of Next where `swc_core` was changed, but for user it's might be not clear because they will try to find the release version of Next and will not be able to do so.

**Comment by kdy1** [comment]
Yeah, I realized there’s some problem in the UX, but wasn’t sure. Thanks! I’ll see if it’s possible to sort by time.

**Comment by kdy1** [comment]
Closing as it's fixed by several commits to the website and data updater.

- Sort by semver: https://github.com/swc-project/website/commit/29133d3cf6e4839069b3354af256bd1a60766fb8
- Fix data updater: https://github.com/swc-project/crawl-core-version/commit/74c03fac1dfe2a861c763d99f88c1c160167edba
