### ISSUE TITLE
Fix build failure

### ISSUE THREAD

**Issue by 9oelM** [swc-project/website#43]
error logs: https://github.com/swc-project/website/runs/2958415071?check_suite_focus=true

**Comment by 9oelM** [comment]
As expected in #42, the deployment didn't go right. 😂 
Let me figure things out.

**Comment by kdy1** [comment]
I tried updating dependencies

**Comment by kdy1** [comment]
And it worked. Thank you a lot 👍

**Comment by kdy1** [comment]
Hmm... Sidebars are flattened. Do you have any idea?

**Comment by 9oelM** [comment]
let me check

**Comment by kdy1** [comment]
I fixed it. Sorry I forgot lefting a comment on this thread.

**Comment by 9oelM** [comment]
Okay. Great to see that the REPL is finally live. I will push more commits for improvements in the future. Thank you.
