### ISSUE TITLE
REPL / playground

### ISSUE THREAD

**Issue by dy** [swc-project/website#6]
I believe that is must-have feature.
Should we organize one @kdy1?

**Comment by kdy1** [comment]
I agree that it's a must have feature, but it requires lot of work.
Some code copied from rustc which lives in swc_common cannot be compiled to wasm target

**Comment by shadowtime2000** [comment]
Any update on this? Can it still not compile to WASM?

**Comment by kdy1** [comment]
`@swc/wasm` exists, but I'm too busy to build a REPL

**Comment by 9oelM** [comment]
As discussed from https://github.com/swc-project/swc/issues/50, I will start porting the website on https://9oelm.github.io/swc-wasm-demo/ into this repository
