### ISSUE TITLE
SWC.rs does not load 

### ISSUE THREAD

**Issue by krrishh-org** [swc-project/website#70]
<img width="1476" alt="Screenshot 2021-08-16 at 11 00 48 AM" src="https://user-images.githubusercontent.com/19912501/129515496-ef804968-707b-4d7f-a7f1-472a85a73342.png">

SWC.rs site doesn't load for me. My network is fine, and all other websites are working fine.

**Comment by kdy1** [comment]
I disabled the proxy of cloudflare.
I'm not sure why I enabled it, but it should be fixed when the dns record change is published
